### ISSUE TITLE
More explanation about the relation to symmetric interaction combinators

### ISSUE THREAD

**Issue by WorldSEnder** [MaiaVictor/Symmetric-Interaction-Calculus#3]
The readme mentions

https://github.com/MaiaVictor/Symmetric-Interaction-Calculus/blob/1e74be3666bf616fe2fc2b3b401db72d67a22c2d/README.md#L17

I've read the blogpost and the linked paper but were not able to find specifics about this. The reason I ask is because I'd love to visualize programs in the combinator form to build intuition. Can you clarify?

**Comment by VictorTaelin** [comment]
Yes, `λx. term` (lambdas) and `(term term)` (applications) are just `δ` nodes, and `(term,term)` and `let (p,q) = term in term` is just a textual visualisation for `ζ` nodes. In order to convert a symmetric interaction net to ASIC, you start traversing it from a wire, then, whenever you find a `δ` node, if you entered it through a main port, you write a `λ` (recursing towards the right port, which is its body, extending a context with the left port); if you entered it through a right port, you write an application (recursing towards the main and right ports, which are its function and argument); if you entered it through a left port, you write a variable (by looking up the context). Similarly, if you find a `ζ` node, you write a pair if you entered it through the main port, and you write a `let` otherwise. This calculus's reduction rules coincide with interaction combinator reductions. As such, both systems are actually the same. This project is just a λ-flavoured stringification of symmetric interaction combinators.

**Comment by VictorTaelin** [comment]
There are some small problems, though. For example, this textual notation can't represent a pair which connects to itself. For that, the syntax would need to be extended with names for each part of the pair; something like: `(a: b, b: a)`...

**Comment by Trebor-Huang** [comment]
If there are slight discrepancies, then why is it claimed that it is "directly isomorphic to Symmetric Interaction Combinators"? Is the isomorphism written down explicitly somewhere? Is it proved that other discrepancies do not arise?

**Comment by Trebor-Huang** [comment]
For example, what if you entered through the left port of a `δ` node that you never entered before? This is possible: consider the graph corresponding to `(λx. x) (λx. x)`, and take its mirror image. If I understand everything correctly, interaction calculus is a useful textual calculus inspired by, but **distinct from**, symmetric interaction combinators. And I don't see any not non-trivial way to amend them so that they become isomorphic.
